<TestLog><TestSuite name="Master Test Suite"><TestCase name="sync_wait" file="exit_code.cpp" line="31"><Info file="exit_code.cpp" line="41"><![CDATA[check !ec has passed]]></Info><Info file="exit_code.cpp" line="46"><![CDATA[check 123 == exit_code has passed]]></Info><TestingTime>36000</TestingTime></TestCase><TestCase name="async_wait" file="exit_code.cpp" line="80"><Info file="exit_code.cpp" line="98"><![CDATA[check !ec has passed]]></Info><Info file="exit_code.cpp" line="60"><![CDATA[check !ec has passed]]></Info><Info file="exit_code.cpp" line="62"><![CDATA[check GetExitCodeProcess(handle_, &exit_code) has passed]]></Info><Info file="exit_code.cpp" line="63"><![CDATA[check 123 == exit_code has passed]]></Info><TestingTime>28000</TestingTime></TestCase></TestSuite></TestLog>